name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: set -o pipefail
      - run: corepack enable

      - uses: actions/setup-node@main
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - run: pnpm install

      - name: npm publish
        run: |
          cp LICENSE dist/
          cd dist/
          npm config set 'https://registry.npmjs.org/:_authToken' '${NODE_AUTH_TOKEN}'
          npm publish --provenance --access=public --tag ${{ inputs.npm_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
